// shop-react/src/LoginComponent.js
import React, { Component } from 'react';
import ReactDOM from 'react-dom';
import './LoginComponent.css';
import DashboardComponent from './DashboardComponent.js'

class LoginComponent extends Component {

  constructor(props) {
    super(props);

    this.state = {
      username: '',
      password: '',
      validUsername: true,
      validPassword: true,
      validLogin: true
    };

    this.handleChange = this.handleChange.bind(this);
    this.handleSubmit = this.handleSubmit.bind(this);

  }

  handleChange(event) {

    if (event.target.id === 'username') {

      this.setState({
        username: event.target.value
      });

    } else if (event.target.id === 'password') {

      this.setState({
        password: event.target.value
      });

    }

  }

  handleSubmit(event) {

    var validForm = true;

    if (this.state.username === '') {

      this.setState({
        validUsername: false
      });

      validForm = false;

    } else {

      this.setState({
        validUsername: true
      });

    }

    if (this.state.password === '') {

      this.setState({
        validPassword: false
      });

      validForm = false;

    } else {

      this.setState({
        validPassword: true
      });

    }

    if (validForm) {

      this.performLogin(this.state.username, this.state.password);

    }

    event.preventDefault();

  }

  performLogin(username, password) {

    ReactDOM.render(
      <DashboardComponent />,
      document.getElementById('root')
    );

  }

  render() {

    var { Grid, Row, Col, FormGroup, FormControl, ControlLabel, Alert } = require('react-bootstrap');

    return (

      <div className="fondo">
        <Grid>

          <Row className="white-text justify-content-center">

            <Col lg={6} xsOffset={3}>

              <h1 className="text-center">Inicia Sesión</h1>

              <form className="form" onSubmit={this.handleSubmit}>

                <FormGroup>
                  <ControlLabel htmlFor="username">Nombre de usuario</ControlLabel>
                  <FormControl id="username" type="text" placeholder="Usuario:" onChange={this.handleChange} value={this.state.username} />
                  {!this.state.validUsername &&
                    <ControlLabel className="error">Debes ingresar un nombre de usuario Válido</ControlLabel>
                  }
                </FormGroup>

                <FormGroup>
                  <ControlLabel htmlFor="password">Nombre de usuario</ControlLabel>
                  <FormControl id="password" type="password" placeholder="Contraseña:" onChange={this.handleChange} value={this.state.password} />
                  {!this.state.validPassword &&
                    <ControlLabel className="error">Debes introducir una contraseña válida</ControlLabel>
                  }
                </FormGroup>

                {!this.state.validLogin &&
                  <Alert bsStyle="warning">
                    <span className="glyphicon glyphicon-ban-circle"></span> El usuario o contraseña no son correctos!
                    </Alert>
                }

                <FormGroup>
                  <button type="submit" className="btn btn-success" name="button">Ingresar</button>
                </FormGroup>

              </form>

            </Col>

          </Row>

        </Grid>

      </div>

    );

  }

}

export default LoginComponent;

// ShopAngular/src/app/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { User } from '../model/User';
import { LoginService } from '../login.service'
import { SessionService } from '../session.service'
import { Router } from '@angular/router'

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {

  title = 'Login';

  user = {
    username: '',
    password: ''
  };

  validUsername = true
  validPassword = true

  validLogin = true

  constructor(
    private loginService: LoginService,
    private sessionService: SessionService,
    private router: Router
  ) { }

  ngOnInit() {

    this.performLogin("user", "pass");

  }

  submitForm(form) {

    let validForm = true

    if (this.user.username == "") {
      this.validUsername = false
      validForm = false
    } else {
      this.validUsername = true
    }

    if (this.user.password == "") {
      this.validPassword = false
      validForm = false
    } else {
      this.validPassword = true
    }

    if (validForm) {

      this.performLogin(this.user.username, this.user.password);

    }

  }

  performLogin(username: string, password: string) {

    this.loginService.performLogin(username, password).subscribe(data => {

      let user: User = {
        username: data.username,
        token: data._kmd.authtoken
      }

      this.sessionService.user = user;

      this.router.navigate(['./dashboard']);

    }, error => {

      this.validLogin = false;

    })

  }

}

<div class="container-fluid background">

  <div class="row white-text justify-content-center">

    <div class="col-6 align-self-center">

      <h1 class="text-center">Inicia Sesión</h1>

      <form class="form" (ngSubmit)="submitForm(f)" #f="ngForm">

        <div class="form-group">
          <label for="username"> Usuario:</label>
          <input class="form-control" placeholder="Usuario" type="text" [(ngModel)]="user.username" name="username" required>
          <label *ngIf="!validUsername" class="error">Debes introducir un nombre de usuario válido</label>
        </div>

        <div class="form-group">
          <label for="password"> Contraseña:</label>
          <input class="form-control" placeholder="Contraseña" type="password" [(ngModel)]="user.password" name="password" required>
          <label *ngIf="!validPassword" class="error">Debes introducir una contraseña válida</label>
        </div>

        <div class="alert alert-warning" *ngIf="!validLogin">
          <span class="glyphicon glyphicon-search" aria-hidden="true"></span>!El usuario o contraseña no son correctos
        </div>

        <div class="form-group text-center">
          <button type="submit" class="btn btn-success" name="button">Ingresar</button>
        </div>

      </form>

    </div>

  </div>

</div>
