// shop-react/src/ProductItemComponent.js
import React, { Component } from 'react';

class ProductItemComponent extends Component {

    constructor(props) {
        super(props)

        this.state = {
            product: props.product
        };
    }

    render() {
        return (

            <div class="bordered">

                <img src="../../assets/{{product.image}}" alt="image {{product.name}}" height="150" width="100%" />

                <h4>{ this.state.product.name }</h4>

                <h6><strong>Precio:</strong> { this.state.product.price }</h6>

                <h6> <strong> Unidades disponibles: </strong> { this.state.product.stock }</h6>

                <a routerLink="/productDetail/{{product.id}}"> <button type="button" class="badge badge-primary">Ver más</button> </a>

                <button type="button" class="badge badge-warning">Añadir</button>

                <input type="number" class="" />

            </div>

        );
    }

}

export default ProductItemComponent;

// ShopAngular/src/app/product-item/product-item.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { Product } from '../model/Product';

@Component({
  selector: 'app-product-item',
  templateUrl: './product-item.component.html',
  styleUrls: ['./product-item.component.css']
})
export class ProductItemComponent implements OnInit {

  @Input()
  product: Product;

  purchaseQuantity: number;

  constructor() {

    this.purchaseQuantity = 0;

  }

  ngOnInit() {
  }

}

<div class="bordered">

  <img src="../../assets/{{product.image}}" alt="image {{product.name}}" height="150" width="100%" />

  <h4>{{product.name}}</h4>

  <h6><strong>Precio:</strong> {{product.price | currency}}</h6>

  <h6> <strong> Unidades disponibles: </strong> {{product.stock}}</h6>

  <button type="button" class="badge badge-primary">Ver más</button>

  <button type="button" class="badge badge-warning">Añadir</button>
  <input type="number" class="" [(ngModel)]="purchaseQuantity" maxlength="4" size="4">


</div>
